# Generated by Django 3.1.4 on 2021-01-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairdresser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=255)),
                ('behandelingen', models.CharField(max_length=800)),
                ('dag', models.CharField(max_length=10)),
                ('datum', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('fname', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=255)),
                ('tijd', models.CharField(max_length=20)),
            ],
        ),
    ]
