# Generated by Django 3.1.4 on 2021-01-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairdresser', '0003_reservering_tijdvakje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservering',
            name='tijdvakje',
            field=models.CharField(max_length=20),
        ),
    ]
