# Generated by Django 3.1.4 on 2020-12-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairdresser', '0003_klant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leeftijd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nulelf', models.CharField(max_length=1)),
                ('twaalfachtien', models.CharField(max_length=1)),
                ('negentienvijfentwintig', models.CharField(max_length=1)),
                ('zesentwintigvijftig', models.CharField(max_length=1)),
                ('vijftigplus', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='klant',
            name='leeftijdscategorie',
            field=models.CharField(default='', max_length=25),
        ),
    ]
