# Generated by Django 3.1.3 on 2020-12-09 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hairdresser', '0004_auto_20201209_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=30, verbose_name='Voornaam')),
            ],
        ),
        migrations.CreateModel(
            name='Behandeling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behandeltype', models.CharField(max_length=30, verbose_name='type')),
                ('tijdsduur', models.DurationField()),
                ('prijs', models.FloatField()),
                ('kapper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hairdresser.kapper')),
            ],
        ),
    ]
