# Generated by Django 3.1.4 on 2021-01-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairdresser', '0004_auto_20210121_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservering',
            name='tijdvakje',
        ),
        migrations.AddField(
            model_name='reservering',
            name='tijdsvakje',
            field=models.CharField(default='', max_length=20),
        ),
    ]
