# Generated by Django 3.1.4 on 2020-12-10 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hairdresser', '0005_behandeling_kapper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behandeling',
            name='kapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hairdresser.kapper'),
        ),
    ]
