# Generated by Django 3.1.4 on 2020-12-11 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hairdresser', '0006_auto_20201210_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behandeling', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hairdresser.behandeling')),
                ('klant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hairdresser.klant')),
            ],
        ),
    ]
