# Generated by Django 3.1.4 on 2020-12-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairdresser', '0007_reservering'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservering',
            name='gehelebehandeling',
            field=models.DurationField(default=''),
        ),
    ]
