# Generated by Django 3.1.4 on 2020-12-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hairdresser', '0008_reservering_gehelebehandeling'),
        ('hairdresser', '0008_reservering_geheletijdsduur'),
    ]

    operations = [
    ]
