# Generated by Django 3.1.4 on 2020-12-16 13:25

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('hairdresser', '0009_merge_20201216_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klant',
            old_name='name',
            new_name='naam',
        ),
        migrations.RemoveField(
            model_name='klant',
            name='leeftijdscategorie',
        ),
        migrations.RemoveField(
            model_name='reservering',
            name='gehelebehandeling',
        ),
        migrations.AddField(
            model_name='klant',
            name='leeftijd',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='klant',
            name='telefoon',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, unique=True),
        ),
    ]
